### ISSUE TITLE
`static_assert` is not yet available in Fuchsia's vanilla C toolchain

### ISSUE THREAD

**Issue by noncombatant** [boringssl/boringssl#4]
I hope I am interpreting this right. When trying to build BoringSSL's HEAD in the Fuchsia tree, I get:

```
[8308/77146] CC kernel.phys32/obj/third_party/boringssl/src/crypto/chacha/boringssl.chacha.c.o
FAILED: kernel.phys32/obj/third_party/boringssl/src/crypto/chacha/boringssl.chacha.c.o 
../../prebuilt/third_party/goma/linux-x64/gomacc ../../prebuilt/third_party/clang/linux-x64/bin/clang -MD -MF kernel.phys32/obj/third_party/boringssl/src/crypto/chacha/boringssl.chacha.c.o.d -o kernel.phys32/obj/third_party/boringssl/src/crypto/chacha/boringssl.chacha.c.o -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -DTOOLCHAIN_VERSION=r2G18YIAK34NbwRXt2sm5ZlMA0QhhvPDqM5Ccy24kRQC -DZX_ASSERT_LEVEL=2 -DHARDEN_SLS -DKERNEL_RETPOLINE=1 -DX64_KERNEL_JCC_WORKAROUND -DLK_DEBUGLEVEL=2 -DWITH_FRAME_POINTERS=1 -DBORINGSSL_NO_CXX -DOPENSSL_NO_ASM -DOPENSSL_NO_THREADS_CORRUPT_MEMORY_AND_LEAK_SECRETS_IF_THREADED -I../../zircon/system/public -I../../third_party/boringssl/src/include -I../../zircon/kernel/lib/crypto/boringssl -I../../zircon/kernel/lib/ktl/include -I../../sdk/lib/stdcompat/include -I../../zircon/kernel/lib/libc/include -gdwarf-4 -Xclang -debug-info-kind=constructor -g3 -fdata-sections -ffunction-sections -O2 -Wall -Wextra -Wconversion -Wextra-semi -Wimplicit-fallthrough -Wnewline-eof -Wstrict-prototypes -Wwrite-strings -Wno-sign-conversion -Wno-unused-parameter -Wnonportable-system-include-path -ftrivial-auto-var-init=pattern -ffile-compilation-dir=. -no-canonical-prefixes -fvisibility=hidden -Wthread-safety -Werror -Wno-error=deprecated-declarations -Wa,--fatal-warnings -fno-common -fsized-deallocation --target=x86_64-fuchsia -fcrash-diagnostics-dir=clang-crashreports -march=x86-64-v2 -mtune=generic -mbranches-within-32B-boundaries -fcolor-diagnostics -fcrash-diagnostics=all -ffreestanding -include ../../zircon/kernel/include/hidden.h -fno-unwind-tables -mno-red-zone -Wformat=2 -Wmissing-declarations -Wvla -Wshadow -mno-red-zone -mfsgsbase -msoft-float -mno-mmx -mno-sse -mno-sse2 -mno-3dnow -mno-avx -mno-avx2 -mcmodel=kernel -mharden-sls=all -mretpoline -mbranches-within-32B-boundaries -fsanitize=undefined -fsanitize-trap=undefined -m32 -fno-pic -fno-pie -msse -mcx16 -mstack-alignment=16 -fsanitize=safe-stack -fno-omit-frame-pointer -Wno-conversion -Wno-unused-but-set-variable -Wno-unused-function -Wno-extra-semi -idirafter ../../zircon/kernel/lib/libc/limits-stub -std=c11 -Wmissing-prototypes -c ../../third_party/boringssl/src/crypto/chacha/chacha.c
In file included from ../../third_party/boringssl/src/crypto/chacha/chacha.c:22:
../../third_party/boringssl/src/crypto/chacha/../internal.h:926:3: error: call to undeclared function 'static_assert'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
```

(and the same error for other files)

`static_assert` is obviously legal C++, and will be legal in C23 (https://en.cppreference.com/w/c/language/_Static_assert), but until then I think vanilla C should use `_Static_assert`. Now, `static_assert` *does* build with my gLinux' clang (interestingly, even without `-std=c2x`), but I guess not in Fuchsia's toolchain.

Should we (Fuchsia) patch BSSL locally to change `static_assert` → `_Static_assert` (which does work), or here upstream? Or am I holding it wrong? There are only 2 instances in the 1 file, so it's easy enough either way.

**Comment by davidben** [comment]
https://bugs.chromium.org/p/boringssl/issues/list is the bug tracker we normally use, BTW. I didn't realize we had the bugtracker on in this one!

Anyway, `static_assert` exists as of C11. It's a macro from `<assert.h>`. The change in C23 is only that it becomes a keyword as it should have been from the beginning. But, either way, a compliant C11 toolchain, which we require if you're not MSVC, is expected to have working `static_assert`. See, from the link you provided:

> This keyword is also available as convenience macro static_assert, available in the header <assert.h>. (until C23)

And then the "since C23" block replaces that by saying `static_assert` is now also the keyword. In fact, we cannot use the `_Static_assert` version because older MSVC doesn't have it. Instead, MSVC has long implemented the C23 behavior of making `static_assert` a normal keyword because their C++ implementation bled through to C.

Though I'm confused why you're only seeing two of them. We're quite liberal using them. (Undercounted because there are also C .h files.)
```
$ git grep static_assert -- '*.c' | wc -l
      86
```

**Comment by noncombatant** [comment]
It's sounding like the issue is that the build failure occurs in Zircon, where a different assert.h holds sway, and that we'll fix it on our end. Thanks!
